fix: fix schema subject names for Topic and TopicRecord strategies
Farfetch/kafka-flow pull request #217
Opened 2021-08-17 02:20 UTC by jplumhoff

# Description

Added topic property to ISerializerContext to make topic available to ConfluentSerializerWrapper and ConfluentDeserializerWrapper.  This allows for the topic name to be used to build the subject name for a schema when using the Topic or TopicRecord subject name strategies.

Fixes #216 

## How Has This Been Tested?

I ran the KafkaFlow.Sample.Avro project with the topic, record, and topicrecord subject naming strategies.  I verified that in each case, 
 - messages were produced and consumed properly
 - schemas were added to the schema registry under the expected subject names.

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have added tests to cover my changes
-   [ ] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2021-08-17 15:41 UTC, dougolima requested changes
Hi @jplumhoff, thanks for the contribution.

Can you please fix the unit tests?

2021-08-17 18:24 UTC, jplumhoff commented
@dougolima - Absolutely!  I've started looking at it, but I need to get familiar with how the tests work.  I might have a few questions for you on slack later.

2021-08-18 02:01 UTC, jplumhoff commented
@dougolima - I believe I've corrected the tests as requested, and I took the opportunity to also clean up some missing comments.  Please let me know if I need to make further changes.

2021-08-19 13:04 UTC, dougolima approved these changes

2021-08-19 13:06 UTC, dougolima commented
> @dougolima - I believe I've corrected the tests as requested, and I took the opportunity to also clean up some missing comments. Please let me know if I need to make further changes.

Nice job @jplumhoff! Thanks for your contribution.

2021-08-19 13:18 UTC, merged